### ISSUE TITLE
HA v2021.6.0 broke the Ryboi custom component

### ISSUE THREAD

**Issue by w00dwork** [Madj42/ryobi_gdo3#3]
Hi Justin,
First off, thanks for putting this integration together.  It's awesome and I've been using it for a couple months now without issue, but...all of my Ryobi entities disappeared after upgrading to the latest 2021.6.0 Home Assistant release today.

From my Home Assistant logs: ![ryboi-error](https://user-images.githubusercontent.com/66153633/120579654-e61d0f00-c3f5-11eb-88eb-855852ddc7ec.png)

Confirmed in the release notes that there was a breaking change :(  
https://www.home-assistant.io/blog/2021/06/02/release-20216/#other-breaking-changes

Apparently there needs to be a valid version key in the master file.  I'm not programmer, so i don't know what's involved with this.  Is this something i can fix?  Something you can help with?  I'd appreciate the assist!

**Comment by Madj42** [comment]
You have an older version of the code.  Please redownload the files and replace the ones you have.  The version key is in the manifest.json file.

**Comment by Madj42** [comment]
No problem at all.  Thanks for reporting back so quickly that it's working.
