### ISSUE TITLE
doorid.py returns bad unique door id and missing files with HACS

### ISSUE THREAD

**Issue by tomasro** [Madj42/ryobi_gdo3#5]
print(doorval[1]) returns 'deviceTypeIds': ['gdoMasterUnit']
print(doorval[0]) returns [{'_id': '*******************'

Can doorid.py be updated? 

Also py_ryobi_gdo.py doesn't install with HACS to custom components/ryobi_gdo3/ folder

**Comment by tomasro** [comment]
Actually doorval[0] returns the userid, where I guess the integration wants the varname, which is actually doorval[5]

**Comment by louisvernon** [comment]
I ran into the device ID issue today. I had two issues
- I had two devices returned and the first wasn't a "gdoMasterUnit" so the device ID for the first device did not work
- The logic to extract the device ID returned the wrong field

I thought about making a PR to change the device ID extraction logic to the following:

```
s = requests.get('https://tti.tiwiconnect.com/api/devices',params=uandp)

for result in s.json()['result']:
  if 'gdoMasterUnit' in result['deviceTypeIds']:
    print(result['metaData']['name'], '- Device ID:',  result['varName'])
```
This will list all your garage door openers with their name. For me this prints:
`My Garage Door Opener - Device ID: ab0a1b8e5bf2`

But you could probably just pprint.pprint(s.json()) and tell users to get the Device ID from the varName field manually.

Other than that this project worked great. I did not have the missing file issue.

**Comment by Madj42** [comment]
> I ran into the device ID issue today. I had two issues
> 
> * I had two devices returned and the first wasn't a "gdoMasterUnit" so the device ID for the first device did not work
> * The logic to extract the device ID returned the wrong field
> 
> I thought about making a PR to change the device ID extraction logic to the following:
> 
> ```
> s = requests.get('https://tti.tiwiconnect.com/api/devices',params=uandp)
> 
> for result in s.json()['result']:
>   if 'gdoMasterUnit' in result['deviceTypeIds']:
>     print(result['metaData']['name'], '- Device ID:',  result['varName'])
> ```
> 
> This will list all your garage door openers with their name. For me this prints: `My Garage Door Opener - Device ID: ab0a1b8e5bf2`
> 
> But you could probably just pprint.pprint(s.json()) and tell users to get the Device ID from the varName field manually.
> 
> Other than that this project worked great. I did not have the missing file issue.

Throw one in if you want.  I haven't had much time to devote to learning more python and adding more features to this.  I merged your last PR and put a pre-release out.  I'll run it for a week and throw it out as a production release after.  Thanks for adding to this!

**Comment by Madj42** [comment]
Closing.
